"""empty message

Revision ID: 47a8131da8b7
Revises: c433ae71a607
Create Date: 2020-05-03 18:37:53.800790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47a8131da8b7'
down_revision = 'c433ae71a607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('favorite', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
